theme: jekyll-theme-cayman
title: Beginner German
description: This is my page for SML5202 assesment about learning German
github:
    Home: Home.html
    Grammar: Grammar.html
    Vocabulary: Vocabulary.html
    More Exercises: MoreExercises.html
    Where Next?: WhereNext?.html
