theme: jekyll-theme-cayman
title: Beginner German
description: This is my page for SML5202 assesment about learning German
github:
    Home: index.html
    Grammar: grammar.html
    Vocabulary: vocabulary.html
    MoreExercises: more-exercises.html
    WhereNext: where-next.html
